services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uv run /code/transactions/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=django_db
      - DJANGO_DB_USER=django_user
      - DJANGO_DB_PASSWORD=django_password

volumes:
  postgres_data: